language: go

go:
  - "1.3.x"  # Used in Debian Jessie  (oldstable).
  - "1.7.x"  # Used in Debian Stretch (stable).
  - "1.10.x" # Used in Debian Buster  (testing).
  - "1.11.x"
  - master

matrix:
  allow_failures:
    - go: master

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-ci"
    template:
      - "%{repository} %{branch} %{commit} - %{author}: %{commit_subject}"
      - "Build #%{build_number} %{result}. Details: %{build_url}"
    on_success: change
    on_failure: change
